export const CONFIG = {
  CANVAS: {
    HEIGHT: 700,
    LETTER_SIZE: 30,
    INTERACTION_RADIUS: 30
  },
  PHYSICS: {
    GRAVITY: 0.5,
    FRICTION: 0.7,
    BOUNCE: -0.5,
    SETTLE_THRESHOLD: 1
  },
  LIMITS: {
    MAX_LETTERS: 500,
    MAX_LINES: 200
  },
  ANIMATION: {
    CONVERSION_INTERVAL: 60
  }
}; 